// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfXqqvyrAU5hGVrSV03syJZHWFDqXtSk',
    appId: '1:28024157066:web:e92e8c10a5c9bd0f574e73',
    messagingSenderId: '28024157066',
    projectId: 'baladna-go',
    authDomain: 'baladna-go.firebaseapp.com',
    storageBucket: 'baladna-go.appspot.com',
    measurementId: 'G-W3S0YGED5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmR4VJvYBd4oCSdZbW9qQi1ot8sESsF8k',
    appId: '1:28024157066:android:0947789e690734e3574e73',
    messagingSenderId: '28024157066',
    projectId: 'baladna-go',
    storageBucket: 'baladna-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKg950XCnY1fvHKG8ZRTBcTPLk_QYDGfk',
    appId: '1:28024157066:ios:f4a88c2594c75232574e73',
    messagingSenderId: '28024157066',
    projectId: 'baladna-go',
    storageBucket: 'baladna-go.appspot.com',
    iosBundleId: 'com.example.baladnaGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKg950XCnY1fvHKG8ZRTBcTPLk_QYDGfk',
    appId: '1:28024157066:ios:f4a88c2594c75232574e73',
    messagingSenderId: '28024157066',
    projectId: 'baladna-go',
    storageBucket: 'baladna-go.appspot.com',
    iosBundleId: 'com.example.baladnaGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCfXqqvyrAU5hGVrSV03syJZHWFDqXtSk',
    appId: '1:28024157066:web:44aeb7877b0499e9574e73',
    messagingSenderId: '28024157066',
    projectId: 'baladna-go',
    authDomain: 'baladna-go.firebaseapp.com',
    storageBucket: 'baladna-go.appspot.com',
    measurementId: 'G-KEP8P5PH25',
  );
}
